import { storage } from "./storage.js";
const languages = ["en", "fa", "ar", "es", "fr", "de", "tr", "sv", "et", "ja", "ko", "zh", "it"];
const languageNames = { en: "English", fa: "فارسی", ar: "العربية", es: "Español", fr: "Français", de: "Deutsch", tr: "Türkçe", sv: "Svenska", et: "Eesti", ja: "日本語", ko: "한국어", zh: "中文", it: "Italiano" };
const footerTranslations = { en: { donate: "Donate", version: "Version 1.0.0" }, fa: { donate: "حمایت مالی", version: "نسخه ۱.۰.۰" }, ar: { donate: "تبرّع", version: "الإصدار ١.٠.٠" }, es: { donate: "Donar", version: "Versión 1.0.0" }, fr: { donate: "Faire un don", version: "Version 1.0.0" }, de: { donate: "Spenden", version: "Version 1.0.0" }, tr: { donate: "Bağış yap", version: "Sürüm 1.0.0" }, sv: { donate: "Donera", version: "Version 1.0.0" }, et: { donate: "Anneta", version: "Versioon 1.0.0" }, ja: { donate: "寄付", version: "バージョン 1.0.0" }, ko: { donate: "후원", version: "버전 1.0.0" }, zh: { donate: "捐赠", version: "版本 1.0.0" }, it: { donate: "Dona", version: "Versione 1.0.0" } };
const $ = id => document.getElementById(id);
let settings, t, running = false, round = 0, position = 0, direction = 1, target = 50, width = 28, speed = 40, last = 0, raf = 0, precisionStreak = 0;
let vazirFontReady;
function ensureVazirFont() { if (!vazirFontReady) { const face = new FontFace('Vazirmatn', 'url("font/Vazirmatn.woff2") format("woff2")', { weight: '400', style: 'normal' }); vazirFontReady = face.load().then(font => { document.fonts.add(font); return font; }); } return vazirFontReady; }
const game = $("gameView"), settingsView = $("settingsView"), stop = $("stopButton");
async function loadTranslations(lang) { const useVazirmatn = ["fa", "ar"].includes(lang); document.documentElement.lang = lang; document.documentElement.classList.toggle('fa-font', useVazirmatn); document.body.style.setProperty('font-family', useVazirmatn ? "'Vazirmatn', sans-serif" : '', 'important'); if (useVazirmatn) await ensureVazirFont(); const messages = await (await fetch(`_locales/${lang}/messages.json`)).json(); t = { ...footerTranslations[lang], ...Object.fromEntries(Object.entries(messages).map(([key, value]) => [key, value.message])) }; document.documentElement.lang = lang; document.documentElement.dir = ["fa", "ar"].includes(lang) ? "rtl" : "ltr"; document.querySelectorAll("[data-i18n]").forEach(e => e.textContent = t[e.dataset.i18n] || e.textContent); document.querySelectorAll("[data-i18n-aria]").forEach(e => e.setAttribute("aria-label", t[e.dataset.i18nAria] || "")); }
function renderRecords() { ["bestScore", "bestPrecision", "bestPrecisionStreak", "gamesPlayed"].forEach(k => { $(k).textContent = k === "bestPrecision" ? `${settings[k].toFixed(1)}%` : String(settings[k]); }); }
function renderGame(score = 0, streak = 0, accuracy) { $("score").textContent = String(score); $("streak").textContent = String(streak); $("accuracy").textContent = accuracy == null ? "—" : `${accuracy.toFixed(1)}%`; }
function paint() { $("marker").style.left = `${position}%`; $("target").style.left = `${target - width / 2}%`; $("target").style.width = `${width}%`; }
function frame(now) { if (!running) return; const dt = Math.min((now - last) / 1000, .05); last = now; position += direction * speed * (settings.reducedMotion ? .55 : 1) * dt; if (position >= 100) { position = 100; direction = -1; } if (position <= 0) { position = 0; direction = 1; } paint(); raf = requestAnimationFrame(frame); }
function beep(ok) { if (!settings.sound) return; const ac = new AudioContext(), o = ac.createOscillator(), g = ac.createGain(); o.frequency.value = ok ? 620 : 180; g.gain.setValueAtTime(.06, ac.currentTime); g.gain.exponentialRampToValueAtTime(.001, ac.currentTime + .12); o.connect(g).connect(ac.destination); o.start(); o.stop(ac.currentTime + .12); }
function resetGame() { running = false; cancelAnimationFrame(raf); round = 0; position = 0; direction = 1; target = 50; width = 28; speed = 40; precisionStreak = 0; renderGame(); paint(); stop.textContent = t.start; document.getElementById("resultLabel").textContent = t.ready; document.getElementById("precision").textContent = "—"; }
function start() { if (running) return finish(); running = true; if (round === 0) { settings = { ...settings, gamesPlayed: settings.gamesPlayed + 1 }; storage.set({ gamesPlayed: settings.gamesPlayed }); renderRecords(); } document.getElementById("resultLabel").textContent = t.go; document.getElementById("precision").textContent = ""; stop.textContent = t.stop; position = 0; direction = 1; last = performance.now(); raf = requestAnimationFrame(frame); }
async function finish() { if (!running) return; running = false; cancelAnimationFrame(raf); const distance = Math.abs(position - target), precision = Math.max(0, 100 * (1 - distance / (width / 2))), success = distance <= width / 2, score = success ? Number($("score").textContent) + Math.round(precision * (1 + round * .12)) : 0, streak = success ? Number($("streak").textContent) + 1 : 0; precisionStreak = precision >= 95 ? precisionStreak + 1 : 0; const label = precision >= 98 ? "perfect" : precision >= 90 ? "excellent" : precision >= 75 ? "great" : success ? "good" : "miss"; $("resultLabel").textContent = t[label]; $("precision").textContent = `${precision.toFixed(1)}%`; renderGame(score, streak, precision); beep(success); round = success ? round + 1 : 0; speed = success ? Math.min(125, speed + 8) : 40; width = success ? Math.max(9, width - 2) : 28; target = success ? 18 + ((target * 1.618 + 23) % 64) : 50; paint(); stop.textContent = t.next; settings = { ...settings, bestScore: Math.max(settings.bestScore, score), bestPrecision: Math.max(settings.bestPrecision, precision), bestPrecisionStreak: Math.max(settings.bestPrecisionStreak, precisionStreak) }; await storage.set(settings); renderRecords(); }
async function init() { settings = await storage.get(); await loadTranslations(settings.language); const select = $("language"); languages.forEach(l => select.add(new Option(languageNames[l], l))); select.value = settings.language; $("sound").checked = settings.sound; $("reducedMotion").checked = settings.reducedMotion; renderRecords(); renderGame(); paint(); stop.addEventListener("click", start); document.getElementById("resetButton").addEventListener("click", resetGame); document.addEventListener("keydown", e => { if ((e.code === "Space" || e.key === "Enter") && settingsView.hidden) { e.preventDefault(); start(); } }); $("settingsButton").onclick = () => { game.hidden = true; settingsView.hidden = false; }; $("backButton").onclick = () => { game.hidden = false; settingsView.hidden = true; }; select.onchange = async () => { settings.language = select.value; await storage.set({ language: settings.language }); await loadTranslations(settings.language); stop.textContent = running ? t.stop : t.next; };["sound", "reducedMotion"].forEach(id => $(id).addEventListener("change", async () => { settings[id] = $(id).checked; await storage.set({ [id]: settings[id] }); })); }
init();
